#!/usr/bin/env sh

sbcl --load ps-helpers.lisp \
     --eval '(compile-ps-file-to loader.parenscript loader.s)' \
     --noinform \
     --disable-ldb \
     --lose-on-corruption

CODE=$(cat loader.js)

curl -d compilation_level=SIMPLE_OPTIMIZATIONS \
     -d output_format=text \
     -d output_info=compiled_code \
     -d js_code='$CODE' \
     http://closure-compiler.appspot.com/compile >> loader.min.js