#!/usr/bin/env sh

# TODO: make script to compile parenscript -> js

CODE=$(cat loader.js)

curl -d compilation_level=SIMPLE_OPTIMIZATIONS \
     -d output_format=text \
     -d output_info=compiled_code \
     -d js_code='$CODE' \
     http://closure-compiler.appspot.com/compile >> loader.min.js